name: Tests

on:
  push:
    branches: [ master, offline ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Debug info
      run: |
          echo "Running pwd..."
          pwd
          echo "\nRunning echo $USER..."
          echo $USER
          echo "\nRunning chown..."
          sudo chown -R -H -L $USER:$USER  /home/runner/work/salmon/
          chown -R -H -L $USER:$USER /home/runner/work/salmon/
          echo "\nRunning chmod..."
          sudo chmod -R 777 /home/runner/work/salmon/
          echo "\nRunning `ls`..."
          ls
    - name: Prepare for docker build...
      run: |
          chmod +x launch.sh
          # chown -R -H -L $USER:$USER .
          sudo chown -R -H -L $USER:$USER .
          sudo chown -R -H -L $USER:$USER salmon docs tests
    - name: Install dependencies
      run: |
        pip install -r offline.txt
    - name: Install Salmon
      run: pip install .
    - name: Run tests in salmon/salmon/
      run: sudo /usr/share/miniconda/bin/pytest salmon/
    - name: Run all tests
      run: sudo /usr/share/miniconda/bin/pytest tests/test_offline.py
